; star we know you're here just get tf out 😘
; if you are deciding to skid this you will get touched 
; zerrox likes femboys

[/Script/FortniteGame.FortGlobals]
bAllowLogout=true

[/Script/FortniteGame.FortTextHotfixConfig]
+TextReplacements=(Category=Game, Namespace="LoadingScreen", bIsMinimalPatch=True, Key="Connecting", NativeString="CONNECTING", LocalizedStrings=(("en","Launching JennaProxy")))
+TextReplacements=(Category=Game, Namespace="LoadingScreen", bIsMinimalPatch=True, Key="LoadingScreenWaitingForPSO", NativeString="PREPARING SHADERS", LocalizedStrings=(("en","Launching JennaProxy")))
+TextReplacements=(Category=Game, Namespace="FortLoginStatus", bIsMinimalPatch=True, Key="LoggingIn", NativeString="Logging In...", LocalizedStrings=(("en","Why are you here?")))

+TextReplacements=(Category=Game, bIsMinimalPatch=True, Namespace="", Key="C87986DE4542C0450F7EA1AC940B8F0D", NativeString="DRAT! WE'RE SORRY", LocalizedStrings=(("en","JENNAPROXY")))
+TextReplacements=(Category=Game, bIsMinimalPatch=True, Namespace="", Key="4A40FB5E4D1A000D740EB18B21C70CE9", NativeString="UH OH!  SOMETHING GOOFED", LocalizedStrings=(("en","JENNAPROXY")))
+TextReplacements=(Category=Game, bIsMinimalPatch=True, Namespace="", Key="1B9B2D834DA0883E9514348620A95123", NativeString="WHOOPS!", LocalizedStrings=(("en","JENNAPROXY")))
+TextReplacements=(Category=Game, bIsMinimalPatch=True, Namespace="", Key="E1FD8EAB445872DB7AF2209988DA1C93", NativeString="THAT WASN'T SUPPOSED TO HAPPEN", LocalizedStrings=(("en","JENNAPROXY")))
+TextReplacements=(Category=Game, bIsMinimalPatch=True, Namespace="", Key="E211A281448782354CD492AFB98CCE7B", NativeString="WE HIT A ROADBLOCK", LocalizedStrings=(("en","JENNAPROXY")))
+TextReplacements=(Category=Game, bIsMinimalPatch=True, Namespace="", Key="96CCC52841C1364F2BB12184E3CB2396", NativeString="NOT THE LLAMA YOU'RE LOOKING FOR", LocalizedStrings=(("en","JENNAPROXY")))
+TextReplacements=(Category=Game, bIsMinimalPatch=True, Namespace="", Key="47218EFD4023FB7C729C71A3A83FF01D", NativeString="THERE WAS A PROBLEM", LocalizedStrings=(("en","JENNAPROXY")))
+TextReplacements=(Category=Game, bIsMinimalPatch=True, Namespace="", Key="10D2167A4B5AFCAB75963CBC54D06038", NativeString="THERE WAS AN ERROR", LocalizedStrings=(("en","JENNAPROXY")))

+TextReplacements=(Category=Game, bIsMinimalPatch=True, Namespace="Fortnite.MatchmakingText", Key="Header.MatchmakingError.Number", NativeString="Matchmaking error (#1)", LocalizedStrings=(("en","JennaProxy")))
+TextReplacements=(Category=Game, bIsMinimalPatch=True, Namespace="Fortnite.MatchmakingText", Key="FailedToConnectToMMS", NativeString="We had trouble talking to the matchmaker. Give it another shot, but if the problem continues, check out {CheckStatusURL}.", LocalizedStrings=(("en","Don't even think about it nigga.")))

+TextReplacements=(Category=Game, bIsMinimalPatch=True, Namespace="", Key="02CB6359405F165C6FE334B84D6C11A7", NativeString="Not Ready", LocalizedStrings=(("en","Nigga Why??")))
+TextReplacements=(Category=Game, bIsMinimalPatch=True, Namespace="", Key="789C71BA479BCADE46E5E2AA4B949075", NativeString="Ready", LocalizedStrings=(("en","Nice Try")))
+TextReplacements=(Category=Game, bIsMinimalPatch=True, Namespace="", Key="997FC44A475797222C307487DBCBF971", NativeString="Disconnected", LocalizedStrings=(("en","Shitty WiFi")))

+TextReplacements=(Category=Game, bIsMinimalPatch=True, Namespace="", Key="DE9C14F147190A1A2D00F7A1D5D8C94C", NativeString="Wednesday Addams", LocalizedStrings=(("en","sizzy's Bitch")))
+TextReplacements=(Category=Game, bIsMinimalPatch=True, Namespace="", Key="06A56ED0441757D5ADD807B1040482C2", NativeString="Santa 'Brina", LocalizedStrings=(("en","foxud's Bitch")))

[/Script/FortniteGame.FortOnlineAccount]
bEnableEulaCheck=false
bShouldCheckIfPlatformAllowed=false